### ISSUE TITLE
Styling, "you can use bbcode" too close to text field.

### ISSUE THREAD

**Issue by thei0173** [Nordic-T/nt-vanilla#10]
https://cloud.githubusercontent.com/assets/13933731/9430049/af60a772-49e6-11e5-9fac-72d11898edf0.png

the text "you can use bb code" is in field of the textbox
seems only an issue when creating or editing OP

**Comment by exetico** [comment]
![skaermbillede 2015-09-03 kl 20 36 49](https://cloud.githubusercontent.com/assets/3549445/9667351/8cc7844a-527b-11e5-98d1-7c7417882c06.png)
