### ISSUE TITLE
Dusty's Feedback

### ISSUE THREAD

**Issue by Dustynt** [Nordic-T/nt-vanilla#11]
<b><h2>Nordic-T v2:</h2></b>Her kommer en beskrivelse af, hvordan min oplevelse med det nye site er indtil videre. Jeg tager generelt udgangspunkt i forbedringer, som skal øge brugervenligheden, og hjemmesidens funktionalitet. Nogle af de ting jeg nævner, er muligvis allerede på tegnebrættet eller på To Do listen.
<br>Dokumentet vil blive  opdateret løbende:
<b>Sidst opdateret: 24.08.2015 kl: 13:45</b>

Browser benyttet til testning: <ins>Firefox 40.0.2</ins>
Styresystem: <ins>Windows 10 Pro 64 bit</ins>
Skærmopløsning: <ins>1900x1200</ins>
Zoom på siden: <ins>180%</ins>
<h2>Hjemmesidens struktur & indstillinger:</h2></b>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Dynamisk tilpasning:</b>
Der er allerede dynamisk tilpasning på siden kan jeg se. Den fungere faktisk udmærket. Men jeg synes stadigvæk at jeg får alt for meget luft mellem tekst og elementer, samt ude i siderne, på en opløsning som hedder 1900x1200. Jeg har tilpasset siden ved at benytte zoom i min browser, og siden er nu som jeg enlig ønsker det. 

Måske den dynamiske tilpasning med tiden kan justeres.  Jeg tror de fleste vil løse tilpasningen med zoom. Det er efter min mening ikke værd at bruge tid på at tilpasse det nu, men i stedet have det i baghovedet, også se hvad brugerne melder tilbage, når det endelige site åbner. Hvis der er et generelt ønske blandt brugerne, kan man tag det med i overvejelserne i fremtiden.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Brugermenu:</b>
Jeg har opdaget at hvis man klikker på ikonerne, fx Bookmarks, skal man trykke på ikonet igen for at lukke den. Man kan ikke bare trykke på selve siden, ikke engang ESC virker. Det vil være rart at kunne lukke den ned med et museklik (og ESC) på et uvilkårligt sted.

<b>OBS</b>: Problemet gør sig også gældende, hvis du trykker på tandhjulet uden for et opslag på forum forsiden.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Indbakke ikon/funktion:</b>
Når man trykker på indbakken, får man en liste frem over de beskeder der er.
Selve opsætningen er super, og den er helt igennem overskuelig. Dog nager det mig, at jeg SKAL trykke på den gule tekst, for at kunne komme ind og læse beskeden.  Jeg vil gerne have, at hele området for den enkelte besked er klikbart. 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Ændring af adgangskode:</b>
Beskeden der fortæller at din adgangskode er blevet ændret, vises nede i bunden og forsvinder efter min mening for hurtigt. Jeg foreslår at den i stedet kommer frem i toppe, over formularen hvor du kan ændre adgangskoden, for på den måde vil brugeren være sikker på, at den er ændret.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Auto log ud ved ændring af koden:</b>
Da jeg ændrede min adgangskode, blev jeg ikke logget ud af siden igen. Jeg foreslår at man sammen med beskeden ”Din adgangskode blev ændret”, samtidig får evt. en ”Popup” boks, som siger noget i stil med 

<i>”Systemet logger dig nu automatisk af, brug den nye adgangskode til at logge på igen”</i>

Hvor efter man skal trykke OK som eneste mulighed. Hvor det også er det eneste man kan. Skulle man vælge at lukke fane eller browser ned, vil man selvfølgelig skulle logge ind på ny.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br><b><h2>Forum og indstillinger:</h2></b>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Forum forsiden:</b>
Har jeg allerede oprettet en tråd på, og den kan ses her: https://github.com/Nordic-T/nt-vanilla/issues/7 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Citering og tag af medlemmer mangler:</b>
Det er ikke muligt at citerer opslag eller en kommentar fra andre. Denne funktion går jeg selvfølgelig ud fra er på vej. Inde på det nuværende Nordic-T, er det muligt at hvis man skriver @, vil der automatisk blive foreslået en bruger, når man skriver det første bogstav. Det er en ret smart funktion, som jeg savner på det nye Nordic-T.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Emner og Indlæg pr. side.</b>
Jeg savner muligheden for selv at kunne vælge, om der skal vises, 10, 20, 30, 40, 50, 100 emner og indlæg pr. side. Disse to funktioner skal være uafhængig af hinanden. Sådan at jeg kan vælge fx 10 Emner pr. side, og 20 Indlæg pr. side.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Dato og klokke på et opslag/svar:</b>
Jeg mangler at kunne se hvornår et opslag blev postet, og hvornår de enkelte svar/kommentarer er skrevet. Lige nu kan man kun se klokkeslettet for hvornår det er oprettet.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Signatur:</b>
Jeg foreslår at vi får muligheden for, at sætte signatur på vores profil. Som vil kunne ses i bunden hver gang man skriver et opslag/kommentar
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<br>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
<b>-	Dobbelt post:</b>
Jeg foreslår at i stedet for at gøre dobbelt post forbudt. Vil det være smartere at programmere systemet til, at flette dobbelt post sammen til en. De har et ligne system over på Nxtgn, som fungere på den måde, at hvis jeg kommenterer på en post, og efterfølgende skriver endnu en post, men der er ikke kommet nogen nye svar siden jeg skrev den første. Så vil systemet automatisk flette den ny post sammen med den gamle post, hvilket betyder at i stedet for 2 poste fra samme bruger, er der kun 1.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

//////////////////////////////////////////////////////////////////////////////////////////
Det hvad jeg har lige nu, jeg opdateret dokumentet, 
efterhånden som finder mere der er værd at nævne :)
//////////////////////////////////////////////////////////////////////////////////////////

**Comment by fbjerggaard** [comment]
Lækker feedback! 

Dynamisk tilpasning - hvor meget har du zoomet for at få det som du gerne vil have det?

Brugermenu - har jeg selv haft tænkt på også.

Ændring af adgangskode - Jeg ser på om vi kan flytte notifikationen.
Hvad vil du opnå ved at logge ud efter skift af adgangskode? Personligt synes jeg det er irriterende når en side gør det :)

Lige præcis signaturer har vi haft oppe og vende tidligere, og det tror jeg ikke umiddelbart vi sætter på. 

Quotes er vi klar over mangler, men der er en bug i quote-pluginnet som vi skal have kigget på.

Man kan stadig tagge medlemmer, men der kommer ingen dropdown - regner dog med at kigge på om der findes et plugin til det.

Emner og indlæg per side bliver nok ikke noget vi får implementeret lige foreløbigt da det som jeg ser det vil kræve ret meget. Det kunne dog helt sikkert være fedt ja.

Tid på posts: Det står der da allerede? 
![image](https://cloud.githubusercontent.com/assets/1044024/9439019/63f7464c-4a63-11e5-96dd-5533bc2a0987.png)
Dog vil der kun stå en dato såfremt det er en anden dag det er skrevet - mener du så at der skal stå det fulde timestamp altid? 

Doubleposts: Jeg har researchet lidt og ikke fundet et plugin der kan det endnu, så enten skal vi lave det selv eller leve med doubleposts - det tænker jeg lige over.

**Comment by Dustynt** [comment]
Det var så lidt, glad for du kan lide det :)

<b>Dynamisk tilpasning:</b> Jeg kører med et zoom på 180% 

<b>Brugermenu:</b> Det glæder mig at høre :)

<b>Ændring af adgangskode:</b> Sikkerhed min ven, jeg ser helst at en hjemmeside logger mig ud, når jeg ændre adgangskoden, da jeg går op i sikkerhed, og derfor vil jeg gerne logges ud. Men det er jo en smagssag :)

<b>Signatur:</b> Af hvilken årsag skyldes den beslutning :( ?

<b>Citering og tag:</b> Jeg havde også regnet med at det ville komme. Er skam klar over at man godt kan tag ved at skrive @, det er bare den fine dropdown menu, som jeg synes vil være trist at miste. De har den også herinde, så et plugin må kunne findes derude :)

<b>Emner og indlæg pr side:</b> Udover arbejdet i at sætte det op, kan jeg ikke se hvad det eller skulle tag, det jo ikke fordi den ekstra data vil fylde særlig meget i SQL. Jeg forventer dog ikke at det skulle ske her og nu, det er som et forslag til fremtidige forbedringer, er det hele :)

<b>Tid og dato:</b> Ja det er korrekt at du kan se klokken, hvilket jeg også skriver. Men hvornår er den oprettet? I dag i går, for 1 år siden? Jeg mangler dato, ellers kan du jo ikke vide om du kigger på en gammel eller ny tråd. Du kan bare se den er oprettet kl. 05:42 am, men det er klokken da forhåbentlig også i morgen, så ja jeg vil gerne have der står dato lige gyldigt om du er tråd starter, eller en der kommenterer.

<b>Dobbelt post:</b> I kan vel også tag fat i staff på Nxtgn, og hører hvordan de gjorde. Kan ikke se hvorfor de ikke vil være interesseret i at hjælpe jer. Efter hvad jeg har hørt, er nogle af deres staff også brugere på NT. Jeg ved bare ikke hvem de er :)

**Comment by exetico** [comment]
Hej @Dustynt 

Kunne jeg få dig til at kigge din feedback igennem, og dertil nævne ting du gerne vil have kigget på?

Vi vil meget gerne se på det - Men jeg vil gerne have det lidt mere i punktform nu :)

**Comment by exetico** [comment]
Da der ikke er kommet flere inputs, lukkes der hermed.
