### ISSUE TITLE
Plugins to install

### ISSUE THREAD

**Issue by fbjerggaard** [Nordic-T/nt-vanilla#12]
* http://vanillaforums.org/addon/mentionslookup-plugin
* http://vanillaforums.org/addon/cleditor-plugin
* http://vanillaforums.org/addon/mentionsplus-plugin

**Comment by Hamderjyden** [comment]
Det med at man kan nævne users blot ved @ er genialt og skal helt klart også indføres i V2

**Comment by exetico** [comment]
Det kommer også, 100p!:)
