### ISSUE TITLE
Mange farver

### ISSUE THREAD

**Issue by Hamderjyden** [Nordic-T/nt-vanilla#13]
Jeg syntes generelt der er alt for mange farver, når man er inde i et topic. Det er simpelthen fovirrende. se eksempel:
http://imgur.com/7dXaC2r

**Comment by Dustynt** [comment]
Hvorfor uploadede du ikke billedet direkte her til i stedet :)

Du skal bare trykke på 
<b>Attach images by dragging & dropping or selecting them</b>

Billedet kan ses længere nede her nu :)
Jeg har allerede indeunder posten med forum forsiden, nævnt at jeg synes ikke om ikon farverne, da de skaber mere forvirring end de gavner. Jeg er derfor enig med dig, og har også forslået at man benytter andre farver, som passer mere ind i designet :)

![7dxac2r](https://cloud.githubusercontent.com/assets/13934115/9441047/011948b6-4a74-11e5-857c-ac820be05fb7.png)

**Comment by Hamderjyden** [comment]
Jep den røde tekst bør ændres til samme farve som normal tekst, evt. en mindre skriftstørrelse også.

Orange links, tænker jeg fint blot kan være links som er understreget (evt. også kursiv).

**Comment by Dustynt** [comment]
Jeg er helt med på ideen med den røde tekst og måske mindre skriftstørrelse, vil gerne se det i action, så det er lettere at vurdere. 

Jeg synes dog de orange links godt at blive, da de derved er letter at finde, og ikke forsvinder i alt teksten. En understreg vil skabe mere forstyrrelse end brugervenlighed.

**Comment by exetico** [comment]
Edited by teksten skal slet ikke være rød ved slutresultatet. Så lige den del, tror jeg er OK. 

Dertil: Hvorfor er i så bange for farver? :-) Der vil være behov for Annoncements markering etc, men de vil jo blive set langt sjældnere end det ses på sitet pt.

**Comment by Dustynt** [comment]
@exetico 
Jeg er ikke bange for farver, med med det layout i har valgt, strider den blå farve i mod alt hvad jeg har lært som web-integrator. Den er i mod de grundlæggende layout regler, som siger at man skal holde sig til den samme farvestil hele vejen igennem. Grundlæggende bruger man normalt max 4 - 5 forskellige farver, der hænger sammen med hinanden.

Jeg kan allerede nu på forum forsiden tælle 8 forskelige farver.
Hvor af Announcement og closed faktisk ikke passer ind. Jeg kan dog godt gå med til den røde farve. 
Men den blå farve, den er simpelthen for meget. Det vil være langt bedre at holde sig til farver som allerede passer ind, og du kan sagtens finde en farve som passer ind, som samtidig vil skabe blikfang.

Jeg har allerede foreslået at gøre Announcement orange i stedet for. Du kan læse om det i mit opslag ang. Forum forsiden. Hvis man nu gør alle ikoner på nær Announcement grå, og bruger en grå farve som allerede er i designet. Så vil du komme ned på 6 farver, og gør du derefter Announcement til en orange farve, så vil den altså skabe blikfang når den fremgår, fordi den ikke er grå lige som alle de andre :)

Det kan ikke skade at give det et forsøg, farven kan altid ændres tilbage igen :)

**Comment by Hamderjyden** [comment]
Syntes heller ikke at alle farve skal væk. Men at have 8 forskellige farver irritere øjnene og skaber et dårligt overblik over siden imo. Kan vildt godt lide det sort/grå og orange tema som I har kørende :) 
I kan evt. spice det op med blå/grønne farver til specielle announments og admin/moderator

**Comment by Dustynt** [comment]
@Hamderjyden Er glad for at se du deler samme holdning. Dog synes jeg ikke det er nogen god ide, at benytte blå/grønne farver til til specielle announments og admin/moderator. For så er vi tilbage hvor vi startede, og problemet vil være det samme. 

Derfor foreslår jeg at alle ikoner på nær announments bliver grå.
Selvfølgelig kan den farve også bruge til "admin" og "Moderator" ikon :)

**Comment by thei0173** [comment]
kunne det være en ide at alle folk med særlige titler blot fik en farve i deres navn? ikke en prangene farve, men bare en lidt mere neutral farve, så fx. exeticos navn vil være mørkegråt, eller grønligt, og members står som de gør nu?

så slippe rman lidt for alt det snuskeri med at de forskellige bokse skal ind i hver post de skriver?

**Comment by Hamderjyden** [comment]
@thei0173 
Den ide kan jeg godt lide :+1:

**Comment by exetico** [comment]
![skaermbillede 2015-09-03 kl 22 29 12](https://cloud.githubusercontent.com/assets/3549445/9670123/4108fd9e-528b-11e5-96b5-735634cf9df6.png)
