### ISSUE TITLE
Tekst generelt

### ISSUE THREAD

**Issue by Hamderjyden** [Nordic-T/nt-vanilla#15]
Hej, jeg har nu kigget lidt rundt på den nye side og generelt fokuseret på tekstformateringen. Der er nogle ting som jeg syntes godt kan ændres.

* <b>Skriftstørrelse:</b>
Generelt syntes jeg skriftstørrelsen er en kende for stor. Jeg legede lidt med zoom-funktionen i Mozilla og ved et zoom på 90% syntes jeg faktisk at det bliver væsentligt bedre:
100%:
![9kzpsam](https://cloud.githubusercontent.com/assets/13945280/9463898/21b4e506-4b20-11e5-8f1e-f94092531254.png)
90%
![sysh38i](https://cloud.githubusercontent.com/assets/13945280/9463912/353cc080-4b20-11e5-9b98-2064244ef0bf.png)
Hvis I mener den lille tekst bliver for lille, kan en mellemting evt. være en løsning.

* <b>Bred, kursiv, understreg osv.:</b>
Her har jeg ingen problemer haft og det fungerer umiddelbart rigtig fint :+1: Det er rart at man nu kan se hvad der er skrevet med fed, det kunne man ikke før. 

* <b>Skriftfarve:</b>
Jeg syntes at hvidt på sort er fint og letlæseligt. Jeg tænker dog at det kunne være rart at have en funktion ligesom på det gamle nt.me hvor man kunne ændre på skriftfarven. Jeg ved ikke om dette blot skal være med kode eller en smart lille dropdown hvor man kan ændre farve. Det var i hvert fald brugbart i nogle sammenhænge førhen.

* <b>Links:</b>
Jeg kunne godt tænke mig at se links være i samme farve som teksten dog understreget og evt. i kursiv også. Jeg tror det vil se væsentligt pænere ud.

* <b>Quotes:</b>
Jeg syntes at quote-systemet fra NT.co V1 fungerede rigtig godt. Det var smart at den indkapslede en del af teksten så det ikke fyldte så meget. Man kunne evt. også lave teksten i en quote mindre så den ikke fylder så meget. 

Det var lige det jeg på stående fod kunne komme frem til. Kommenter gerne hvis folk er (u)enige :)

**Comment by exetico** [comment]
Quote kommer, men er pt. bugged mig bekendt :-) 

Ser på det andet når der er tiden til det.

**Comment by exetico** [comment]
Skriftstørrelse:

Jeg er enig, og har ændret font-size-base til 14px (-1px).

Umiddelbart er det OK - men det kræver ofc. også at andre er enige her.

**Comment by exetico** [comment]
Smid en besked på NT hvis denne skal genåbnes. Vil mene at denne nemlig kan lukkes, så det gør jeg.
