### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by Hamderjyden** [Nordic-T/nt-vanilla#17]
Dette er blot et forslag, men ved ikke hvor vigtigt det er.

Ikonerne for bogmærker er forskellige. Bogmærkefanen er en fane og når man skal bogmærke noget er det en stjerne. Ved ikke om det ville være smart at bruge samme ikon begge steder? :)

![capture](https://cloud.githubusercontent.com/assets/13945280/9482301/f9af5ba4-4b92-11e5-8ea2-dbe4b84e7f74.PNG)

**Comment by exetico** [comment]
Bestemt :-) Det er klart fornuftigt, at vi vælger det samme ikon til begge steder.

**Comment by exetico** [comment]
Stjerne eller det andet ikon (fra topmenuen) @Hamderjyden ?:-)

**Comment by fbjerggaard** [comment]
@exetico - Tænker at bruge det fra topmenuen - det giver umiddelbart mest mening som bookmark :)

**Comment by exetico** [comment]
![skaermbillede 2015-09-03 kl 22 14 00](https://cloud.githubusercontent.com/assets/3549445/9669726/2a5f7fc0-5289-11e5-8cac-d7ab5c606553.png)
Dertil er der fjernet farver fra bookmark, så den har samme farve som Options, samt hover-effekt.
