### ISSUE TITLE
Marker alle som 'Set'

### ISSUE THREAD

**Issue by Spunkit** [Nordic-T/nt-vanilla#19]
Jeg ved ikke om overskriften er forklarende nok, og jeg ved ikke om det bare er mig der ikke har fundet funktionen endnu..
Men jeg mangler altså en eller anden måde at kunne markere alle topic som værende set, således der ikke står New ved dem alle.
Jeg kan personligt godt li at den gamle måde, hvor topic man med nyt indhold siden sidste login, er markeret med fed skrift. Jeg tror dette New badge tricker min ocd eller et eller andet, jeg har hvert fald behov for at få dem alle fjernet.. :|

**Comment by exetico** [comment]
![skaermbillede 2015-09-03 kl 21 09 09](https://cloud.githubusercontent.com/assets/3549445/9668128/0f3d4906-5280-11e5-8b19-e9db9d4fa2fd.png)
Denne mulighed er der - Men det er kun til hver enkelt sub.

Der er lavet til v1 - men virker nok ikke med v2 af Vanilla:
http://vanillaforums.org/addon/348-mark-all-read-redux

Dertil er det i Cloud-løsningen, som endnu en ting der er muligt der:
https://blog.vanillaforums.com/features/mark-all-viewed-top-25-features-for-users/

Vi burde vel kunne det, og kan klart se hvorfor det er et behov :+1:

**Comment by exetico** [comment]
Måske er der noget brugbart her, der virker i den nyeste version?..
http://vanillaforums.org/discussion/23081/mark-read-and-unfollow-drop-down-options-dont-work

**Comment by exetico** [comment]
...
![image](https://cloud.githubusercontent.com/assets/3549445/9669282/52e6404e-5286-11e5-9e6b-b60110a19062.png)
![skaermbillede 2015-09-03 kl 21 53 30](https://cloud.githubusercontent.com/assets/3549445/9669266/4262f4d8-5286-11e5-97f2-f9a4ac1f941e.png)
