### ISSUE TITLE
Popular Tags mangler style

### ISSUE THREAD

**Issue by exetico** [Nordic-T/nt-vanilla#24]
![skaermbillede 2015-09-06 kl 00 11 21](https://cloud.githubusercontent.com/assets/3549445/9701490/dbecf90e-542b-11e5-9a51-933e915d5b66.png)
Spørgsmålet er om de bare skal være Grå, eller om de skal være Orange?

Kom gerne med jeres input, ellers bliver det blot efter mit eget hoved denne gang.

**Comment by Hamderjyden** [comment]
Jeg stemmer helt klart for at vi holder dem lysegrå. Tror det falder for meget i øjnene. Det er blot tags, som egentlig kun er vigtig under søgning osv.

**Comment by exetico** [comment]
![skaermbillede 2015-09-13 kl 17 51 34](https://cloud.githubusercontent.com/assets/3549445/9837472/194f8734-5a40-11e5-97b3-a249575ec05e.png)
Fixed.
