### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by thei0173** [Nordic-T/nt-vanilla#26]
under min account name etc.
![screenshot_2015-09-06-10-49-59](https://cloud.githubusercontent.com/assets/13933447/9703766/f6fab4ae-548d-11e5-814b-25f92cee3d8a.png)

det er lidt svært at se feltet

**Comment by exetico** [comment]
Yeas - Den er jeg OBS på :-) Den er ikke just pæn pt. Når den nok i dag. Roder med top-menuen pt, da jeg ikke er fan af den pt.

**Comment by thei0173** [comment]
pt. og så 3 gange i træk :) 
ville bare lige melde den ind for en sikkerheds skyld over git

**Comment by exetico** [comment]
![skaermbillede 2015-09-06 kl 14 50 58](https://cloud.githubusercontent.com/assets/3549445/9704431/b6de57fe-54a6-11e5-90dc-a6ace26be66c.png)
Har lavet et hurtigt fix pt.

**Comment by exetico** [comment]
Regner med at det her er OK - Genåbn evt. hvis det ikke er tilfældet. Kan ikke huske om jeg har stylet de sidste.
