### ISSUE TITLE
Information omkring upload af profilbillede

### ISSUE THREAD

**Issue by Hamderjyden** [Nordic-T/nt-vanilla#28]
Jeg kunne godt tænke mig lidt info på siden når man vil uploade sit profilbillede. Pt. står der kun max 2mb, men ikke noget med dimensioner eller lign. 

http://v2.nordic-t.co/profile/picture

**Comment by exetico** [comment]
Det er en rigtig god ide. Jeg er sikker på at vi får lavet det, måske ikke ved release - Men det kan nu godt være!
