### ISSUE TITLE
weird white spots

### ISSUE THREAD

**Issue by thei0173** [Nordic-T/nt-vanilla#30]
![screenshot_2015-09-06-20-17-15](https://cloud.githubusercontent.com/assets/13933447/9705898/80b82244-54d4-11e5-9d69-8dfb9eddfa32.png)

der er 2 hvide felter hen over "new message"

er spottet på oneplusone med mobil siden

**Comment by exetico** [comment]
Det er "Inbox" - Prøv lige at se om det sker, efter du har kørt "javascript:location.reload(true)" :-) Burde have rettet det, men måske der er noget jeg lige har overset efterfølgende - Ordnede nemlig et par ting efter.

**Comment by exetico** [comment]
Fixed.
