### ISSUE TITLE
Topmenuen - Box-shadow + text-shadow på ikoner

### ISSUE THREAD

**Issue by exetico** [Nordic-T/nt-vanilla#32]
Hej Alle, 

Hvad synes i om skyggerne på top-menuen? Skal den være mindre? Selv synes jeg den er lidt voldsom, men @fbjerggaard og jeg, er ikke rigtig blevet enige. Dog vil jeg mene at den skal være lidt mindre.

Dertil har vi text-shadow på ikoner og tekst. Egentlig er jeg ikke meget fan af dette.

Hvad synes i?

![image](https://cloud.githubusercontent.com/assets/3549445/9706066/a0c2c792-54d9-11e5-8cfa-2ae5e6e0953b.png)
![image](https://cloud.githubusercontent.com/assets/3549445/9706071/cf39ade8-54d9-11e5-8988-c2e988cecce1.png)

Samme gør sig glædende på knapperne ved posting af comment. Første og anden knap har skygge, "Post Comment" har fået denne fjernet, men har tilsyneladende glemt de andre.
![image](https://cloud.githubusercontent.com/assets/3549445/9706068/ba4748dc-54d9-11e5-8493-7ffd0670ffe0.png)

**Comment by fbjerggaard** [comment]
Lukket - det er fikset af lmndk :)
