### ISSUE TITLE
Avatar på Profil siden.

### ISSUE THREAD

**Issue by supremacy2k** [Nordic-T/nt-vanilla#33]
Har lagt mærke til at profil billedet skalerer med siden.
dvs et billede på f.eks. 50x50px bliver skaleret op i 300x600px (eksempel)

![profile2](https://cloud.githubusercontent.com/assets/11375688/9837477/633214e8-5a40-11e5-9fad-0cbf171b3866.png)
![profile1](https://cloud.githubusercontent.com/assets/11375688/9837478/63344362-5a40-11e5-829f-f739ff2ffdf0.png)

**Comment by exetico** [comment]
Er dette stadig et problem?

**Comment by Thanosdk** [comment]
Ja.

**Comment by Thanosdk** [comment]
Jeg har på slate, gennemtvunget:
width: auto !important;
height: auto !important;

for at billedet bliver vist i original størrelse, i stedet for at den skalerer med siden.
Hvis billedet er småt, bliver det skaleret op mod 7 gange op, og gør det ekstremt pixeleret.

**Comment by exetico** [comment]
Så skal det klart fikses :-)
