### ISSUE TITLE
Quote knap ved comments.

### ISSUE THREAD

**Issue by supremacy2k** [Nordic-T/nt-vanilla#35]
Vi mangler en quote knap, så vi nemt kan quote beskeder.

**Comment by fbjerggaard** [comment]
Quotes plugin findes her:
https://github.com/Nordic-T/nt-vanilla/tree/master/plugins/Quotes
Mindes dog jeg har testet det og det ikke virker på 2.1

**Comment by fbjerggaard** [comment]
Fixed.
