### ISSUE TITLE
Ændringen af dato stempel ved topics/comments

### ISSUE THREAD

**Issue by supremacy2k** [Nordic-T/nt-vanilla#38]
Er det muligt at ændre "datoen" på diverse posts til at være 'I dag'/'i går'/'dato' - tror det ville gøre det væsentligt nemmere og mere overskueligt

plus ændre tiden på topics, til at være hvornår sidste post er skrevet, i stedet for hvornår topic er oprettet

**Comment by fbjerggaard** [comment]
Der er fundet et plugin til det, skal blot lige finde ud af hvordan det fungerer.

**Comment by supremacy2k** [comment]
awesome, det jeg smed i går?

**Comment by fbjerggaard** [comment]
Yep. Det er løst nu!
