### ISSUE TITLE
Text not vissible in Tags input field

### ISSUE THREAD

**Issue by Spunkit** [Nordic-T/nt-vanilla#4]
When creating a new discussion there is a 'Tags' field, when im writing somthing in the field it won't show what im writing.. 
![image](https://cloud.githubusercontent.com/assets/13933731/9430049/af60a772-49e6-11e5-9fac-72d11898edf0.png)

**Comment by fbjerggaard** [comment]
Thanks! Gotta fix that one.

**Comment by exetico** [comment]
![skaermbillede 2015-09-03 kl 20 23 46](https://cloud.githubusercontent.com/assets/3549445/9667035/c6778138-5279-11e5-8ff2-254ca142ebbb.png)
Fixed!

**Comment by exetico** [comment]
![skaermbillede 2015-09-03 kl 20 23 46](https://cloud.githubusercontent.com/assets/3549445/9667035/c6778138-5279-11e5-8ff2-254ca142ebbb.png)
Fixed!
