### ISSUE TITLE
Jump to latest comment.

### ISSUE THREAD

**Issue by supremacy2k** [Nordic-T/nt-vanilla#44]
Nogle brugere oplever at de bliver smidt til sidste post i tråden, i stedet for sidste læste post.

**Comment by fbjerggaard** [comment]
Må være en lokal ting, for jeg oplever altid at blive sendt til nyeste ulæste post.

**Comment by exetico** [comment]
Hvis det skulle genopstå, så genåbn. Lukker herfra.
