### ISSUE TITLE
Header på lav opløsning

### ISSUE THREAD

**Issue by exetico** [Nordic-T/nt-vanilla#50]
Headeren bliver meget høj på lav opløsning/width af browser.

![image](https://cloud.githubusercontent.com/assets/3549445/10056286/bdc9fa54-623a-11e5-8dba-b442305cc526.png)

Der er flere muligheder...

- Vi kan ændre på headeren - F.eks. fjerne "Nordic Tommunity", eller replace det med en lille tekst ved lav opløsning i stedet.
- Vi kunne lade "collapsed" menu vises tidligere end den gør pt. (Det er jeg selv imod).
- Vi kunne evt. forkorte "Categories", "Discussions", "Actity" og "Mark All Viewed" med Ikoner som på mobile.

Hvad synes i?

@fbjerggaard @Nordic-T/administrators @Nordic-T/gitters @Nordic-T/owners @Nordic-T/web-developers

**Comment by fbjerggaard** [comment]
Synes godt vi kan have det som udelukkende ikoner

**Comment by exetico** [comment]
Fint.

Jeg vil meget gerne have forslag til ikonerne.
