### ISSUE TITLE
[Styling/CSS] Cancel button when editing comment

### ISSUE THREAD

**Issue by Spunkit** [Nordic-T/nt-vanilla#6]
The cancel button is too close to the 'Save comment'-button, mybe add some 

margin-right: 10px;

![image](https://cloud.githubusercontent.com/assets/13933731/9430144/6fa0f278-49ea-11e5-9847-1ce67ed80ddf.png)

**Comment by exetico** [comment]
Well. It need space, but guess we will following one of the defaults. The whole theme is generated by LESS. But... You're right, that it doesn't look nice at all. Going to fix that :-)

**Comment by fbjerggaard** [comment]
I suggest we give it a button-style-thingy like the "Save Comment" button, but with a read-thingy-thingy.. :) 
And then of course spacing it apart from each other.

**Comment by Dustynt** [comment]
Jeg er for træt til engelsk :P
Men jeg synes faktisk det er bedst at holde cancel som en tekst knap, for på den måde kan du lettere kende forskel på dem, og risikoen for at trykke forkert er mindre. :)

**Comment by exetico** [comment]
Her er jeg helt enig i, at jeg synes vi skal holde det som en tekst. Andet gavner ikke.

**Comment by exetico** [comment]
Jeg fikser det nu - Spørgsmålet er om vi evt. skal give den en hvid tekst i stedet for orange? Kom gerne med input @Spunkit @Dustynt @fbjerggaard 

- Jeg mener fortsat at den skal have plane-text style, og ikke være en knap. Men farven...?:-)

**Comment by exetico** [comment]
https://i.imgur.com/ISqVvKD.png

Fixed!

Hvis i har bud på et andet "edit ikon", så skal i finde et her:
http://astronautweb.co/snippet/font-awesome/
