### ISSUE TITLE
Warnings synlighed i forum

### ISSUE THREAD

**Issue by exetico** [Nordic-T/nt-vanilla#8]
Vi skal have lavet en løsning hvor der ikke står de tunge tekster - men spørgsmålet er hvordan det løses bedst? 

Har i forslag til visningen, der kan vises i tre forskellige 'levels', så byd endelig ind. 

Eksempel fjernet, men tilføjes igen i morgen, når jeg får tid til at  klippe det efter hensigten.

**Comment by Dustynt** [comment]
Jeg er ikke sikker på om jeg forstår spørgsmålet, og om der er tale om det jeg selv foreslår med overblik i forummet? :)

**Comment by thei0173** [comment]
lige p.t. kan jeg så berette at der er en fed gul boks med en "MILD" i sig, + en trekant, hvis du ser mit nick i Hej Testere.

**Comment by Dustynt** [comment]
@thei0173 Hos mig  ser du  bare så ledes ud :)
![theif0173](https://cloud.githubusercontent.com/assets/13934115/9437088/7c3cc790-4a54-11e5-80bf-0c5b72c9bf45.jpg)

**Comment by Hamderjyden** [comment]
Syntes også et lille ikon ved siden af username ville være fint :)

**Comment by exetico** [comment]
@Dustynt  - Spændende.... Måske andre ikke kan se at man har en warning så? Det er egentlig OK for mig, efter nærmere eftertanke.

Kan en af i andre bekræfte det?
@Hamderjyden @christiankm

**Comment by exetico** [comment]
Det lader til kun at være mods+ der kan se disse - Skulle det vise sig at det ikke er korrekt, fikser vi det herefter.
